# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bitsId', models.CharField(max_length=15)),
                ('hostelPs', models.BooleanField()),
                ('gender', models.CharField(max_length=1)),
                ('bDay', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bloodGroup', models.CharField(max_length=3)),
                ('cgpa', models.FloatField()),
                ('admit', models.DateField()),
                ('parentName', models.CharField(max_length=50)),
                ('parentPhone', models.CharField(max_length=20)),
                ('parentEmail', models.CharField(max_length=50)),
            ],
        ),
    ]
