# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=20)),
                ('otherReason', models.CharField(max_length=20, null=True)),
                ('reqDate', models.DateField()),
                ('printed', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chamber', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Login'),
        ),
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Login'),
            preserve_default=False,
        ),
    ]
