# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171027_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(max_length=10),
        ),
    ]
