# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171028_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
    ]
