# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171104_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='dataTimeEnd',
            new_name='dateTimeEnd',
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approvedBy',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='leave',
            name='consent',
            field=models.CharField(choices=[('Letter', 'Letter'), ('Fax', 'Fax'), ('Email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='messoption',
            name='mess',
            field=models.CharField(choices=[('A', 'Dining Hall A'), ('C', 'Dining Hall C')], max_length=1),
        ),
    ]
